### ISSUE TITLE
Problem opeining the http server on windows

### ISSUE THREAD

**Issue by mohasafra** [smiclea/brackets-http-server#5] opened 2015-05-07 11:00 UTC
when the new tab window opens it only shows

Not found see screenshot attached
![screenshot](https://cloud.githubusercontent.com/assets/10555252/7513944/8d95ef98-f4b0-11e4-95f8-be6695896cf3.jpg)

**Comment by smiclea** [comment] 2015-05-13 09:15
That is strange. I'll have a look at it, some colleague of mine was able to reproduce it.

**Comment by mohasafra** [comment] 2015-05-14 08:42
yes exactly I've checked the code me and a couple of friend and we couldn't understand the source of the problem...

**Comment by smiclea** [comment] 2015-05-14 14:03
The problem was that most likely your path contains space. This is now resolved in latest version

**Closed by smiclea** 2015-05-14 14:03 UTC

**Comment by mohasafra** [comment] 2015-05-14 14:46
yep that fixed it thanks a lot for your work
